In [1]:
import joblib
import numpy as np

In [2]:
model_DT = joblib.load('models/model_DT1.pkl')
model_GB = joblib.load('models/model_GB1.pkl')
model_KNN = joblib.load('models/model_KNN1.pkl')
model_LR = joblib.load('models/model_LR1.pkl')
model_RFC = joblib.load('models/model_RF1.pkl')
model_SVM = joblib.load('models/model_SVM1.pkl')


In [3]:
# Target 0 example
input_arr = np.array([41, 1, 0, 1, 96.4, 110, 60, 92, 0]).reshape(1, -1)

# Target 1 example
#input_arr = np.array([32, 0, 1, 1, 100.5, 130, 90, 98, 1]).reshape(1, -1)

In [4]:
def predict(input, model):
    return model.predict(input)

def predict_proba(input, model):
    return model.predict_proba(input)


In [5]:
res_DT = predict(input_arr, model_DT)
print(res_DT)

res_DT_proba = predict_proba(input_arr, model_DT)
print(res_DT_proba)



res_GB = predict(input_arr, model_GB)
print(res_GB)

res_GB_proba = predict_proba(input_arr, model_GB)
print(res_GB_proba)



res_KNN = predict(input_arr, model_KNN)
print(res_KNN)

res_KNN_proba = predict_proba(input_arr, model_KNN)
print(res_KNN_proba)



res_LR = predict(input_arr, model_LR)
print(res_LR)

res_LR_proba = predict_proba(input_arr, model_LR)
print(res_LR_proba)



res_RFC = predict(input_arr, model_RFC)
print(res_RFC)

res_RFC_proba = predict_proba(input_arr, model_RFC)
print(res_RFC_proba)



[0.]
[[1. 0.]]
[0.]
[[1.00000000e+000 3.08332761e-140]]
[0.]
[[0.8 0.2]]
[0.]
[[1.00000000e+000 3.08332761e-140]]
[0.]
[[0.91 0.09]]


In [6]:
ensemble_result = [res_DT_proba[0], res_GB_proba[0], res_KNN_proba[0], res_LR_proba[0], res_RFC_proba[0]]
print(ensemble_result)

output = np.mean(ensemble_result, axis = 0)
print(output)
print('Final Prediction - Class {}'.format(output.argmax()))

[array([1., 0.]), array([1.00000000e+000, 3.08332761e-140]), array([0.8, 0.2]), array([1.00000000e+000, 3.08332761e-140]), array([0.91, 0.09])]
[0.942 0.058]
Final Prediction - Class 0
